quora_app/urls.py
from django.urls import path
from django.shortcuts import redirect
from quora_app.views import (custom_signup,
                             custom_login,
                             question_list,
                             post_question,
                             answer_question,
                             like_answer,
                             custom_logout,
                             user_profile)

def redirect_to_login(request):
    return redirect('/login/')

urlpatterns = [
    path('', redirect_to_login),
    path('signup/', custom_signup, name='signup'),
    path('login/', custom_login, name='login'),
    path('questions/', question_list, name='questions'),
    path('post-question/', post_question, name='post-question'),
    path('answer-question/<int:question_id>/', answer_question, name='answer-question'),
    path('like-answer/<int:answer_id>/', like_answer, name='like-answer'),
    path('logout/', custom_logout, name='logout'),
    path('user-profile/', user_profile, name='user-profile'),
 ]

quora_mock/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quora_app.urls'))
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quora_app/models.py
from django.db import models
from django.contrib.auth.models import User

class BaseModel(models.Model):
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    class Meta:
        abstract = True

class Question(BaseModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=500)

class Answer(BaseModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    likes = models.ManyToManyField(User, related_name='answers_likes')
    content = models.TextField()
    

quora_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Question,Answer

class CustomSignupForm(UserCreationForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder': 'Email'}))

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class CustomLoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Username'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['title']

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']

quora_app/views.py
from django.shortcuts import render,redirect
from django.db.models import Q
from quora_app.forms import CustomSignupForm,CustomLoginForm,QuestionForm,AnswerForm
from django.contrib.auth import login, authenticate,logout
from django.contrib import messages
from quora_app.dbapi import get_all_questions,get_answer,get_question,filter_answer,filter_question
from django.contrib.auth.decorators import login_required

def custom_signup(request):
    if request.method == 'POST':
        form = CustomSignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('questions')
    else:
        form = CustomSignupForm()
    return render(request, 'signup.html', {'form': form})

def custom_login(request):
    if request.method == 'POST':
        form = CustomLoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user:
                login(request, user)
                return redirect('questions')
            else:
                messages.error(request, "Error: Invalid Username or Password")
    else:
        form = CustomLoginForm()
    return render(request, 'login.html', {'form': form})

@login_required
def question_list(request):
    query = request.GET.get('search',"")
    questions = get_all_questions().filter(Q(title__icontains=query)).order_by('-id')
    answers_liked = list()
    if request.user.is_authenticated:
        answers_liked = filter_answer(likes=request.user)
    return render(request, 'questions.html', {'questions': questions,"answers_liked":answers_liked})

@login_required
def post_question(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.user = request.user
            question.save()
            return redirect('questions')
    else:
        form = QuestionForm()
    return render(request, 'post_question.html', {'form': form})

@login_required
def answer_question(request, question_id):
    question = get_question(id=question_id)
    if request.method == 'POST':
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.user = request.user
            answer.question = question
            answer.save()
            return redirect('questions')
    else:
        form = AnswerForm()
    return render(request, 'answer.html', {'form': form, 'question': question})

@login_required
def like_answer(request, answer_id):
    answer = get_answer(id=answer_id)
    if request.user in answer.likes.all():
        answer.likes.remove(request.user)
    else:
        answer.likes.add(request.user)
    request.user.refresh_from_db()
    return redirect('questions')

def custom_logout(request):
    logout(request)
    return redirect('login')

@login_required
def user_profile(request):
    question_asked = filter_question(user=request.user).count()
    answered = filter_answer(user=request.user).count()
    return render(request, 'profile.html', {'question_asked': question_asked, 'answered': answered})

templates/answer.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block content %}
<div class="w-1/3 py-4 px-8 bg-white shadow-lg rounded-lg mx-auto">
<h1 class="font-bold text-cyan-600 text-3xl text-center mb-2">Time to shine! Your answer?</h1>
<h3 class="font-semibold text-gray-600 text-1xl my-4">{{ question.title }}</h3>
<form method="post">
    {% csrf_token %}
    {{ form | crispy}}
    <button
    class="flex w-full mt-10 mb-4 justify-center rounded-md  border-transparent bg-cyan-500 py-2 px-4 text-sm  text-white shadow-sm hover:bg-cyan-600 focus:outline-none focus:ring-2 focus:ring-cyan-400 focus:ring-offset-2 font-semibold"
    type="submit">
    Submit
    </button>
</form>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>askQ</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
<style>
   
    body, html {
        min-height: 100%;
        margin: 0;
        padding: 0;
    }
    body {
        background-image: linear-gradient(to bottom right, rgba(255,0,0,0), #00ADB5);
        overflow: auto; 
    }
</style>
</head>
<body class="bg-color">
    {% if messages %}
    {% for message in messages %}
    
    {% if message.tags == 'error' %}
    <div class="bg-red-100 border-t-4 border-red-500 rounded-b text-red-900 px-4 py-3 shadow-md absolute top-0 left-2/4 -translate-x-2/4 z-50" role="alert">
        <div>
            <p class="font-bold text-center">{{message}}</p>
        
        </div>
      </div>
    {% else %}
    <div class="bg-teal-100 border-t-4 border-teal-500 rounded-b text-teal-900 px-4 py-3 shadow-md absolute absolute top-0 left-2/4 -translate-x-2/4 z-50" role="alert">
        <div>
            <p class="font-bold text-center">{{message}}</p>
            <!-- <p class="text-sm">Make sure you know how these changes affect you.</p> -->
        </div>
      </div>
    {% endif %}

    {% endfor %}

    {% endif %}
        <nav class="bg-gray-50 border-b-2 border-cyan-600">
            <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
            <div class="text-2xl font-extrabold leading-none tracking-tight text-cyan-700 md:text-4xl flex items-center">
                <span>ask</span>
                    <span class="text-cyan-900">Q</span>
            </div>
              <div class="hidden w-full md:block md:w-auto" id="navbar-default">
                <ul class="font-medium flex flex-col p-4 md:p-0 mt-4 border rounded-lg  md:flex-row md:space-x-8 md:mt-0 md:border-0 items-center">
                    {% if user.is_authenticated %}
                    <li>
                    <div class="relative">
                    <form method="GET" action="{% url 'questions' %}">
                    <input class="border-2 border-cyan-600 bg-white h-10 px-5 pr-16 rounded-lg text-sm focus:outline-none"
                    type="search" name="search" placeholder="Search" value="{{ request.GET.search }}">
                    <button type="submit" class="absolute right-0 top-0 mt-3 mr-4">
                    <svg class="text-gray-600 h-4 w-4 fill-current" xmlns="http://www.w3.org/2000/svg"
                    xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Capa_1" x="0px" y="0px"
                    viewBox="0 0 56.966 56.966" style="enable-background:new 0 0 56.966 56.966;" xml:space="preserve"
                    width="512px" height="512px">
                    <path
                    d="M55.146,51.887L41.588,37.786c3.486-4.144,5.396-9.358,5.396-14.786c0-12.682-10.318-23-23-23s-23,10.318-23,23  s10.318,23,23,23c4.761,0,9.298-1.436,13.177-4.162l13.661,14.208c0.571,0.593,1.339,0.92,2.162,0.92  c0.779,0,1.518-0.297,2.079-0.837C56.255,54.982,56.293,53.08,55.146,51.887z M23.984,6c9.374,0,17,7.626,17,17s-7.626,17-17,17  s-17-7.626-17-17S14.61,6,23.984,6z" />
                    </svg>
                    </button>
                    </form>
                    </div>
                    </li>

                  <li>
                    <a href="{% url 'questions' %}" class="block py-2 pl-3 pr-4 text-cyan-600 font-semibold text-xl  md:border-0 md:p-0">Home</a>
                  </li>
                  <li>
                    <a href="{% url 'post-question' %}" class="block py-2 pl-3 pr-4 text-cyan-600 font-semibold text-xl  md:border-0 md:p-0">Post Question</a>
                  </li>
                  <li>
                    <a href="{% url 'user-profile' %}" class="block py-2 pl-3 pr-4 text-cyan-600 font-semibold text-xl  md:border-0 md:p-0">Profile</a>
                  </li>
                  <li>
                    <a href="{% url 'logout' %}" class="block py-2 pl-3 pr-4 text-cyan-600 font-semibold text-xl  md:border-0 md:p-0">Logout</a>
                  </li>
                  {% else %}
                  <li>
                    <a href="{% url 'login' %}" class="block py-2 pl-3 pr-4 text-cyan-600 font-semibold text-xl  md:border-0 md:p-0">Login</a>
                  </li>
                  <li>
                    <a href="{% url 'signup' %}" class="block py-2 pl-3 pr-4 text-cyan-600 font-semibold text-xl  md:border-0 md:p-0">Signup</a>
                  </li>
                  {% endif %}
                </ul>
              </div>
            </div>

    </nav>
    <div class="my-16">
    {% block content %}
    {% endblock %}
    </div>
</body>
</html>

templates/login.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block content %}
<div class="w-1/3 py-4 px-8 bg-white shadow-lg rounded-lg mx-auto">
<h1 class="font-bold text-cyan-600 text-3xl text-center mb-6">Login</h1>
<form method="post">
  {% csrf_token %}
  {{ form | crispy }}

    <button
    class="flex w-full mt-10 mb-4 justify-center rounded-md  border-transparent bg-cyan-500 py-2 px-4 text-sm  text-white shadow-sm hover:bg-cyan-600 focus:outline-none focus:ring-2 focus:ring-cyan-400 focus:ring-offset-2 font-semibold"
    type="submit">
    Login
    </button>
  
</form>
</div>
{% endblock %}

templates/post_question.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block content %}
<div class="w-1/3 py-4 px-8 bg-white shadow-lg rounded-lg mx-auto">
<h1 class="font-bold text-cyan-600 text-3xl text-center mb-8">Curiosity on overdrive? Unleash your question!</h1>
<form method="post">
    {% csrf_token %}
    {{ form | crispy }}
    <button
    class="flex w-full mt-10 mb-4 justify-center rounded-md  border-transparent bg-cyan-500 py-2 px-4 text-sm  text-white shadow-sm hover:bg-cyan-600 focus:outline-none focus:ring-2 focus:ring-cyan-400 focus:ring-offset-2 font-semibold"
    type="submit">
    Post
    </button>
</form>
</div>
{% endblock %}

templates/profile.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block content %}
<div class="flex items-center justify-center gap-x-4">
    <div
		class='flex flex-wrap flex-row sm:flex-col justify-center items-center w-full sm:w-1/4 p-5 bg-white rounded-md shadow-xl border-l-4 border-orange-500'>
		<div class="flex justify-between w-full">
			<div>
				<div class="">
					<span class="material-symbols-outlined w-6 h-6">
                        question_mark
                        </span>
				</div>
			</div>
			
		</div>
		<div class="text-center">
			<div class="font-bold text-5xl">
				{{question_asked}}
			</div>
			<div class="font-bold text-sm">
			 Question Asked
			</div>
		</div>
	</div>
    <div
		class='flex flex-wrap flex-row sm:flex-col justify-center items-center w-full sm:w-1/4 p-5 bg-white rounded-md shadow-xl border-l-4 border-green-500'>
		<div class="flex justify-between w-full">
			<div>
				<div class="">
					<span class="material-symbols-outlined w-6 h-6">
                        done
                        </span>
				</div>
			</div>
			
		</div>
		<div class="text-center">
			<div class="font-bold text-5xl">
				{{answered}}
			</div>
			<div class="font-bold text-sm">
			 Answers
			</div>
		</div>
	</div>

</div>
{% endblock %}

templates/questions.html
{% extends 'base.html' %}

{% block content %}
    {% if questions %}
    {% for question in questions %}
    <div class="w-1/3 py-4 px-8 bg-white shadow-lg rounded-lg my-2 mx-auto">
    <p class="font-semibold text-md mb-1">Posted by: <span class="text-cyan-600">{{ question.user.username }}</span></p>
    <h3 class="font-bold text-gray-600 text-xl mb-4">{{ question.title }}</h3>
    <div class="max-h-40 overflow-y-auto">
    {% for answer in question.answer_set.all %}
    <p class="font-semibold text-gray-600">{{ answer.content }}</p>
              
    <form method="POST" action="{% url 'like-answer' answer.id %}">
    {% csrf_token %}
    <div class="inline-flex gap-x-1 text-xs items-center leading-none uppercase px-6 py-1 rounded-full bg-white text-gray-700 border mt-1 mb-2">
    {% if answer.likes.count%}
    <span class="text-cyan-500 font-semibold text-xl leading-none">{{answer.likes.count}}</span>
    {% else %}
    <span class="text-cyan-500 font-semibold text-xl leading-none">0</span>
    {% endif %}
    <button type="submit" class="mt-1">
    {% if answer in answers_liked %}
    <span class="material-symbols-outlined" style="font-size: 20px;color: red;">
    thumb_up
    </span>
    {% else %}
    <span class="material-symbols-outlined" style="font-size: 20px;">
        thumb_up
    </span>
    {% endif %}
    </button>
    </div>
    </form>
    {% endfor %}
    </div>
    <div class="flex items-center justify-end mt-4">
        <a href="{% url 'answer-question' question.id %}" class="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-cyan-700 rounded-lg hover:bg-cyan-800 focus:ring-4 focus:outline-none focus:ring-cyan-300">
            Answer
            <svg class="w-3.5 h-3.5 ml-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"/>
            </svg>
        </a>
    </div>
    
    </div>
    {% endfor %}
    {% else %}
    <div class="w-1/3 py-4 px-8 bg-white shadow-lg rounded-lg my-2 mx-auto">
        <h1 class="font-bold text-cyan-600 text-3xl text-center mb-6">Zero posts found.<br>Why don't you post something!</h1>
        <a href="{% url 'post-question' %}"><button
        class="flex w-full mt-10 mb-4 justify-center rounded-md  border-transparent bg-cyan-500 py-2 px-4 text-sm  text-white shadow-sm hover:bg-cyan-600 focus:outline-none focus:ring-2 focus:ring-cyan-400 focus:ring-offset-2 font-semibold"
        type="button">Post Question</button></a>
    </div>
    {% endif %}

{% endblock %}

templates/signup.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block content %}
<div class="w-1/3 py-4 px-8 bg-white shadow-lg rounded-lg mx-auto">
<h1 class="font-bold text-cyan-600 text-3xl text-center mb-6">Sign Up</h1>
<form method="POST">
  {% csrf_token %}
  {{ form | crispy}}
  <button
  class="flex w-full mt-10 mb-4 justify-center rounded-md  border-transparent bg-cyan-500 py-2 px-4 text-sm  text-white shadow-sm hover:bg-cyan-600 focus:outline-none focus:ring-2 focus:ring-cyan-400 focus:ring-offset-2 font-semibold"
  type="submit">Sign Up</button>
</form>
<p>Already have an account? <a href="{% url 'login' %}">Log in here</a></p>
</div>
{% endblock %}